### ISSUE TITLE
Update with Modules Example

### ISSUE THREAD

**Issue by kitsu** [cc-tweaked/datapack-example#1]
Thanks for setting up this example repo, but I had an issue using it.

According to what I've read it looks like the old API infrastructure is deprecated, so I wrote a new `require` style module and dropped it in the datapack's api folder. You can probably guess, but I was surprised when requiring it failed.
(I actually had to do some debugging with the datapack, contrary to mc wiki you can't just use a folder, and 7z nests the folder)

After trying a couple things and failing I noticed the paths listed in the require error had `/rom/modules` instead of `/rom/api`, but even after creating  the modules folder and moving my file it still wouldn't load. Turns out I *had* to add another special folder (`main`, `turtle`, or `command`).

It wasn't a big deal, and I figured it out eventually, but it was confusing and might stump someone.

I can try a PR if you want, IDK how fancy I should get though?

**Comment by SquidDev** [comment]
Oh gosh, not having a module is a bit of an oversight on my part. Especially as I'm trying to encourage people to use `require` over APIs :facepalm:. If you're happy to put together a PR, that'd be wonderful!

It really doesn't need to be fancy - have a look at what `my_api` does. I guess something like:

```lua
local function do_something()
    print("Doing something with my_module")
end

return { do_something = do_something }
```

And then maybe in `my-program.lua`

```lua
local my_module = require "my_module"
my_module.do_something()

-- Rest of the file.
```

Might be worth adding a comment to mention `turtle` and `command` also work.
